version: '3.1'
services:
  casdoor:
    restart: always
    container_name: casdoor
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8091:8000"
    depends_on:
      - casdoor-mysql
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf:/conf/

  casdoor-mysql:
    image: mysql:8.0
    container_name: casdoor-mysql
    ports:
      - "3313:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init-sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
